apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spriteforge
resources:
  - resources.yaml
  - sealed-forge-db-owner.yaml
  - sealed-spriteforge-secrets.yaml
  - sealed-forgejo-registry.yaml
  - sealed-cnpg-backup-creds.yaml
