---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spriteforge-secrets
  namespace: spriteforge
spec:
  encryptedData:
    FAL_KEY: AgDU9ucsWXjS8cRFl8WO268ioq1LEhSeePaUpbCtsKqGm30AVqnvqRF79ZNTddD1XCsUAc12TYp9+GK2uMJJ7O1etqbHECb+R+PCH3a0jnujCJhXY0CwKMxHh/8lrtXX74YOX3DDuJdPf/4ddsuzjfQ7IkEghQziZT8ayx+8RyhEwJG1zWTmnpBEPR/JfSz1QDAMMuJ+imUhkIBjrKrv1amEHBP9Qnebnk+c9pbiG3nC1NGYk09y1m1YBqLZna9CxX2Hmdri30z6H1qxWGO8ilnBRyukOhwFfuZZN9pMd1RNXYfheX271w3je2pqyOEUX4RNGPoMKBecys86MMGY1bk/3fFvfhxdxtgzhX7SCKZHmR2Bsc1cFtUufrI4TqPIqDsk39lqfup9jdnowcu+1Nj/cKeYTv6VL5lBnn+tFbuef8GdkTGcS/5ki1Bt4hlWtwyahJrJ8azUXxbDRDcnty2Be5encqmB/tB4Oy8hPNLTwhpxsJBm1vPYuJ6/wGft3wSqgXFJVW5FiEx4sXU84VNTBftLgG8IOQPSZeRTFu1NCOCSVKQTSj/6GpGK0dSiptAT2jI/LrLfX8INHW/aB70lanUzLUlAuOnojjz+p79cI/5cvC/w5OsLHY+SbIUFYnd5lxTr1P7/mRyltyErDNo3AJJHnAaQ+Au8lFEUnebpG2pzW7cJLqZSVMI1+QIfHJe1qwqENzD+4Jd7xlL3NcrLkzG2PcC0pVY4GTd9b5wLBHnMhecbtLBzVw/EtmXfl592oyZBXaqQy2KYVMamJ7eReAiaevA=
    PROVIDER: AgA1/zpsZcCZEPYWNQtde1pVacTZzguLODR9ltuGCC49C1FESzwfQ1hNrtmTFfQF/Pjt7xbvEuyn+zlsptmOHhljXulM4aq7jv6F+K3jTrBCBz5ZBLti5BvS73D40NW60JdIzHgeSIOFKcaA1oOLLCzo0GnJHVAzjm81IoSlLpEWDS34LwFCHYB5JYlmO7Xj9e26LQmB+4XTLXP9vCPBWLmxvvGcescqrAR7fgyZKZm+foVX8HUEVaeM+4TgS7KYeIcSbrWe7WPefHUY/ch+JsiiZq4DvxfW53HH+MnSwBJjmJCXv0F9ehE0wIvR06mLYgUe2avGyfkfR8p0BvotpGMAPBMFPtQp7ZmJtsf+GIYfMj2dxFjQrKdOuSZx4uJGGF57xDea126oqGvc0/VwN1p1ey+gz14SJHAuQ3r+T1PP/9w9pPI6lsJlioUC0HzjYCxBUITAu+PwAWkv8vzt69xUEYsmXjGsYV/j4liYtmi+OPK7cA7/pRNBtcC/YXADMxfMi8sfB3La3Y7d6Zuehuj15m1ad8++w5yfDtN76jsERAWRzVN/Gd8hPp3aT0wEkt2/MM2bgH9Zbssn4I3t2pWQg32sDTr7m8LBVKUjyQ7N6CHfmLNFZaSx9AYsYtJRjvdRLRC1xUyT1FdyFpi6glcAYVAD7iXrtLSWZGP64zhO4SJPBbHKzVYyrR2gjVGH5T+2khQ=
  template:
    metadata:
      creationTimestamp: null
      name: spriteforge-secrets
      namespace: spriteforge
