---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-db-owner
  namespace: spriteforge
spec:
  encryptedData:
    password: AgDRBsZWS6gCBWMrm6LR09KreZXf2/SY6WNIkl462BBF12E3YCtzvHhEYX5BQZyQl+HcGUh8oKlS5exV1XUaAMgCCSWKJ/wl7jr5mUqnhbHcNV2qndsEa+HSg2mXgxGePLfZ1lge5KJlVxZ0K7livQikN8bbp2Hf3gs/mfeRZBcNTtTeg/A8ZrvJY/JYei1QePLouqeFoIc1nEOFmHKrelMLETW0GXCH1m6G0CsDaJMmzVfCmnGI+cxV8GReV23Gge/j+ZSRBAu3+TTQw3jlF1Wc+5ZEQmQV4C5sPxmn10OUfifkUd1DSxRqBHk+uVOPRHMzT09l29lTjGQIM8CG3Sor73yOQHreMcnTeLcHqGkGjm2uJTDHOACVVF8UUECUqw7sQPFdTWmbVpauiPkDD87jMqAZaocOTSKs7gikBEzhQLapK2k5w/r21SZjKY0k2Tt8epWEj/SBgRCSi1ZCpYeSSyRygalO/EloMyoGxw15+GgPm6B4kTXcxR4ysYy823N9ZXNAlBxnSsYit1NuYdm+5chZoDx3EuPexzr0fDtdlFQ2fDhhUe/Qwy89mOLvsZUG6bn3CkxIREuutnwGhvrrHSRTA5DHOeiOFG+ZpJino4hD9+91Jfq0yEh3J+h7WOfLy3UjcGa7lXt6gGD5EdolcHVkyWc3mPurHkkStKvvs61STAi/DA3QYJDBs5BRnynqGlf+9A0rFyE+mEa6I1Q2wDZaHaOFqcB4LPNUQC/igeH/gi86X4VV
    username: AgDFv8aJKzikqdFCCpF2o5EG7BRyXVebDG7NfS3th+S6ywq8vbGQKR83pK4L4QUMToAQUDVCCR/qK2zYWk9WfxBCGRGELACCLz7CP1YRDwQB0R6pXAZaQwhnZe05HoA+Pg5rJVz+06Gsp05G1osGBGacZYoLq8BdM5S7kI2Rn+HTh4OJkWj3MyLVObbqSMSh9L5Mp3Bf0I3q/u0aMvv1cgQhD6iM3RKbZHRcTxe/ry8VXV9B7FRQQ3krk9Eq7C/iu0kGhe7z/0j1CzYOJYqcJ3VxLuqyiAEif0Ank8/GhbwD+c/ZK8Y3kPn/S6NRf+xnF7zW5abKnJJ4wnYicAcfrzOkpCxr+HrR6bd4bU2jWQvq8gx8uuMJFr5ynrOWELSpFVir5psjsN4U3FEV6RzLSpdha8ATvFJp0t7oHeIwgDe132+qmrxACD0q5ui9qnFzHnpCkB+lfpgF3l1RnBS57AsdXM6kWeKeaiJ/pMx/OKajYlHlABp4tghpKBUbJBGdeZxnztbHHzdYS3CHGkwJNdKV2GoJgFM8Kmnr3W5yF9aRyuCWJpaFy6HDJu7cfesw3YtLnU0mEvHgxpu/Eh4UKV0cZ0rvkwOqlpZtHq8HHCMVOFhRvKiCxMOKEhsrKCZjE2Fca7u9MqvvT4s3pY9T4f//VTXrYPNx1BduPwIln5SbPVRhtW9MMMUM/qNo3wrkEktzcrx4Ng==
  template:
    metadata:
      creationTimestamp: null
      name: forge-db-owner
      namespace: spriteforge
